[project]
name = "dialogue-summarizer-lora"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ge78huc", email = "ge78huc@tum.de" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
dialogue-summarizer-lora = "dialogue_summarizer_lora:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
